// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1hgbiBMCNMytB1YB4cku5_GN-luIuI7M',
    appId: '1:2859234896:web:32f3bad10b51f0bd020355',
    messagingSenderId: '2859234896',
    projectId: 'app-top-top',
    authDomain: 'app-top-top.firebaseapp.com',
    storageBucket: 'app-top-top.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeKypHTCYtSXoM8lXvu8Ksfg-U0M3QOro',
    appId: '1:2859234896:android:07326ffd3b953fa3020355',
    messagingSenderId: '2859234896',
    projectId: 'app-top-top',
    storageBucket: 'app-top-top.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC05Yc7rKWVxVDtGSzwq78qonurnh_tH-g',
    appId: '1:2859234896:ios:829970a90a5c3864020355',
    messagingSenderId: '2859234896',
    projectId: 'app-top-top',
    storageBucket: 'app-top-top.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
